# Generated by Django 3.1.1 on 2020-11-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20201109_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
