# Generated by Django 3.1.1 on 2020-11-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='last_payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
