# Generated by Django 3.1.2 on 2020-11-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20201110_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('EL', 'Electrical'), ('PL', 'Plumbing'), ('RE', 'Repairing'), ('IN', 'Internet'), ('OT', 'Other')], default='OT', max_length=200)),
                ('complaint', models.CharField(max_length=200)),
            ],
        ),
    ]
