# Generated by Django 3.1.2 on 2020-11-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_house_e_signature'),
        ('rentals', '0006_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='house',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
    ]
