# Generated by Django 3.1.2 on 2020-11-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_house_e_signature'),
        ('rentals', '0007_complaints_house'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
    ]
