# Generated by Django 3.1.1 on 2020-11-18 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20201116_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
