# Generated by Django 3.1.1 on 2020-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('EL', 'Electrical'), ('PL', 'Plumbing'), ('RE', 'Repairing'), ('Internet', 'Internet'), ('OT', 'Other')], default='OT', max_length=200),
        ),
    ]
