# Generated by Django 3.1.1 on 2020-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20201118_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Repairing', 'Repairing'), ('Internet', 'Internet'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
