# Generated by Django 3.1.2 on 2020-11-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20201015_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(auto_now_add=True)),
                ('complaint_type', models.CharField(choices=[('PL', 'Plumbing'), ('EL', 'Electrical'), ('Rv', 'Renovation'), ('Ot', 'Others')], default='Ot', max_length=200)),
                ('complaint', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
