# Generated by Django 3.1.2 on 2020-11-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_contract'),
        ('users', '0006_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='house',
            field=models.OneToOneField(default=19, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
    ]
