# Generated by Django 3.1.1 on 2020-11-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0012_contract'),
        ('users', '0007_tenant_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='house',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
