# Generated by Django 3.1.2 on 2020-10-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
