# Generated by Django 3.1.2 on 2020-10-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_house_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_slug',
        ),
    ]
