# Generated by Django 3.1.1 on 2020-10-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_house_house_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='house_pics'),
        ),
    ]
