# Generated by Django 3.1.1 on 2020-10-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
    ]
