# Generated by Django 3.1.1 on 2020-10-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20201020_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_pics', to='houses.house'),
        ),
    ]
