# Generated by Django 3.1.2 on 2020-10-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20201020_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='landmark',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('AP', 'Apartment'), ('SG', 'Single Family House'), ('TW', 'Town House'), ('CD', 'Condominiums'), ('BG', 'Bungalow')], default='AP', max_length=200),
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('servant_room', models.BooleanField(default=False)),
                ('gas_pipeline', models.BooleanField(default=False)),
                ('sewage_treatment_plant', models.BooleanField(default=False)),
                ('visitor_parking', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('club_house', models.BooleanField(default=False)),
                ('children_play_area', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('house_keeping', models.BooleanField(default=False)),
                ('internet_services', models.BooleanField(default=False)),
                ('intercom', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
                ('shopping_center', models.BooleanField(default=False)),
                ('rain_water_harvesting', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
    ]
