# Generated by Django 3.1.1 on 2020-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20201025_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='children_play_area',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='club_house',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='fire_safety',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='intercom',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='rain_water_harvesting',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='servant_room',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='sewage_treatment_plant',
        ),
        migrations.AlterField(
            model_name='house',
            name='balcony',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
    ]
