# Generated by Django 3.1.2 on 2020-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20201026_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='tenant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
