# Generated by Django 3.1.1 on 2020-11-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
