# Generated by Django 3.1.1 on 2020-11-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_delete_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='E_Signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
